name: CI & CD Pipelines

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "front/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      wd: ./front
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Import repository code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.14.0'

      - name: Install dependencies
        run: npm ci --include=dev
        working-directory: ${{env.wd}}

      - name: Run CI tests
        run: npm t
        working-directory: ${{env.wd}}
      
      - name: Build code
        run: npm run build
        working-directory: ${{env.wd}}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-duration-seconds: 300

      - name: Push build folder to AWS S3 bucket & invalidate Cloudfront distribution cache
        run: |
          aws s3 rm s3://${{ secrets.S3_BUCKET_NAME }} --recursive
          aws s3 sync ./build/. s3://${{ secrets.S3_BUCKET_NAME }}
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIB_ID }} --paths "/index.html"
        working-directory: ${{env.wd}}
  